# Server address
server_address = "https://sponsor.ajay.app"
# Categories: sponsor, selfpromo, interaction, poi_highlight, intro, outro, preview, music_offtopic, filler, exclusive_access
categories = ["sponsor"]
# Action types: skip, mute, poi, full
action_types = ["skip"]
# Get segments for a video with extra privacy 
privacy_api = false
# Third party YouTube domains like Piped, Invidious or CloudTube
domains = ["piped.kavin.rocks", "invidious.kavin.rocks"]
# Use OSD when a segment is skipped or muted
skip_notice = false
